################################################################################
# Automatically-generated file. Do not edit!
################################################################################

C_UPPER_SRCS := 
CXX_SRCS := 
C++_SRCS := 
OBJ_SRCS := 
CC_SRCS := 
SRC_SRCS := 
CPP_SRCS := 
C_SRCS := 
O_SRCS := 
CC_DEPS := 
C++_DEPS := 
EXECUTABLES := 
C_UPPER_DEPS := 
CXX_DEPS := 
OBJS := 
SECONDARY_SIZE := 
COMPILED_SRCS := 
CPP_DEPS := 
C_DEPS := 

# Every subdirectory with source files must be described here
SUBDIRS := \
CODE/AI \
CODE/Flash \
CODE/ICM \
CODE/Menu \
CODE/PCI \
CODE/PID \
CODE/Special_Control \
CODE/UART \
Libraries/infineon_libraries/Configurations \
Libraries/infineon_libraries/Infra/Platform/Tricore/Compilers \
Libraries/infineon_libraries/Infra/Ssw/TC37A/Tricore \
Libraries/infineon_libraries/Service/CpuGeneric/If \
Libraries/infineon_libraries/Service/CpuGeneric/StdIf \
Libraries/infineon_libraries/Service/CpuGeneric/SysSe/Bsp \
Libraries/infineon_libraries/Service/CpuGeneric/SysSe/Comm \
Libraries/infineon_libraries/Service/CpuGeneric/SysSe/General \
Libraries/infineon_libraries/Service/CpuGeneric/SysSe/Math \
Libraries/infineon_libraries/Service/CpuGeneric/SysSe/Time \
Libraries/infineon_libraries/iLLD/TC37A/Tricore/Asclin/Asc \
Libraries/infineon_libraries/iLLD/TC37A/Tricore/Asclin/Lin \
Libraries/infineon_libraries/iLLD/TC37A/Tricore/Asclin/Spi \
Libraries/infineon_libraries/iLLD/TC37A/Tricore/Asclin/Std \
Libraries/infineon_libraries/iLLD/TC37A/Tricore/Can/Can \
Libraries/infineon_libraries/iLLD/TC37A/Tricore/Can/Std \
Libraries/infineon_libraries/iLLD/TC37A/Tricore/Ccu6/Icu \
Libraries/infineon_libraries/iLLD/TC37A/Tricore/Ccu6/PwmBc \
Libraries/infineon_libraries/iLLD/TC37A/Tricore/Ccu6/PwmHl \
Libraries/infineon_libraries/iLLD/TC37A/Tricore/Ccu6/Std \
Libraries/infineon_libraries/iLLD/TC37A/Tricore/Ccu6/TPwm \
Libraries/infineon_libraries/iLLD/TC37A/Tricore/Ccu6/Timer \
Libraries/infineon_libraries/iLLD/TC37A/Tricore/Ccu6/TimerWithTrigger \
Libraries/infineon_libraries/iLLD/TC37A/Tricore/Convctrl/Std \
Libraries/infineon_libraries/iLLD/TC37A/Tricore/Cpu/Irq \
Libraries/infineon_libraries/iLLD/TC37A/Tricore/Cpu/Std \
Libraries/infineon_libraries/iLLD/TC37A/Tricore/Cpu/Trap \
Libraries/infineon_libraries/iLLD/TC37A/Tricore/Dma/Dma \
Libraries/infineon_libraries/iLLD/TC37A/Tricore/Dma/Std \
Libraries/infineon_libraries/iLLD/TC37A/Tricore/Dts/Dts \
Libraries/infineon_libraries/iLLD/TC37A/Tricore/Dts/Std \
Libraries/infineon_libraries/iLLD/TC37A/Tricore/Edsadc/Edsadc \
Libraries/infineon_libraries/iLLD/TC37A/Tricore/Edsadc/Std \
Libraries/infineon_libraries/iLLD/TC37A/Tricore/Eray/Eray \
Libraries/infineon_libraries/iLLD/TC37A/Tricore/Eray/Std \
Libraries/infineon_libraries/iLLD/TC37A/Tricore/Evadc/Adc \
Libraries/infineon_libraries/iLLD/TC37A/Tricore/Evadc/Std \
Libraries/infineon_libraries/iLLD/TC37A/Tricore/Fce/Crc \
Libraries/infineon_libraries/iLLD/TC37A/Tricore/Fce/Std \
Libraries/infineon_libraries/iLLD/TC37A/Tricore/Flash/Std \
Libraries/infineon_libraries/iLLD/TC37A/Tricore/Geth/Eth \
Libraries/infineon_libraries/iLLD/TC37A/Tricore/Geth/Std \
Libraries/infineon_libraries/iLLD/TC37A/Tricore/Gpt12/IncrEnc \
Libraries/infineon_libraries/iLLD/TC37A/Tricore/Gpt12/Std \
Libraries/infineon_libraries/iLLD/TC37A/Tricore/Gtm/Atom/Pwm \
Libraries/infineon_libraries/iLLD/TC37A/Tricore/Gtm/Atom/PwmHl \
Libraries/infineon_libraries/iLLD/TC37A/Tricore/Gtm/Atom/Timer \
Libraries/infineon_libraries/iLLD/TC37A/Tricore/Gtm/Std \
Libraries/infineon_libraries/iLLD/TC37A/Tricore/Gtm/Tim/In \
Libraries/infineon_libraries/iLLD/TC37A/Tricore/Gtm/Tim/Timer \
Libraries/infineon_libraries/iLLD/TC37A/Tricore/Gtm/Tom/Pwm \
Libraries/infineon_libraries/iLLD/TC37A/Tricore/Gtm/Tom/PwmHl \
Libraries/infineon_libraries/iLLD/TC37A/Tricore/Gtm/Tom/Timer \
Libraries/infineon_libraries/iLLD/TC37A/Tricore/Gtm/Trig \
Libraries/infineon_libraries/iLLD/TC37A/Tricore/Hssl/Hssl \
Libraries/infineon_libraries/iLLD/TC37A/Tricore/Hssl/Std \
Libraries/infineon_libraries/iLLD/TC37A/Tricore/I2c/I2c \
Libraries/infineon_libraries/iLLD/TC37A/Tricore/I2c/Std \
Libraries/infineon_libraries/iLLD/TC37A/Tricore/Iom/Driver \
Libraries/infineon_libraries/iLLD/TC37A/Tricore/Iom/Iom \
Libraries/infineon_libraries/iLLD/TC37A/Tricore/Iom/Std \
Libraries/infineon_libraries/iLLD/TC37A/Tricore/Msc/Msc \
Libraries/infineon_libraries/iLLD/TC37A/Tricore/Msc/Std \
Libraries/infineon_libraries/iLLD/TC37A/Tricore/Mtu/Std \
Libraries/infineon_libraries/iLLD/TC37A/Tricore/Pms/Std \
Libraries/infineon_libraries/iLLD/TC37A/Tricore/Port/Io \
Libraries/infineon_libraries/iLLD/TC37A/Tricore/Port/Std \
Libraries/infineon_libraries/iLLD/TC37A/Tricore/Psi5/Psi5 \
Libraries/infineon_libraries/iLLD/TC37A/Tricore/Psi5/Std \
Libraries/infineon_libraries/iLLD/TC37A/Tricore/Psi5s/Psi5s \
Libraries/infineon_libraries/iLLD/TC37A/Tricore/Psi5s/Std \
Libraries/infineon_libraries/iLLD/TC37A/Tricore/Qspi/SpiMaster \
Libraries/infineon_libraries/iLLD/TC37A/Tricore/Qspi/SpiSlave \
Libraries/infineon_libraries/iLLD/TC37A/Tricore/Qspi/Std \
Libraries/infineon_libraries/iLLD/TC37A/Tricore/Scu/Std \
Libraries/infineon_libraries/iLLD/TC37A/Tricore/Sent/Sent \
Libraries/infineon_libraries/iLLD/TC37A/Tricore/Sent/Std \
Libraries/infineon_libraries/iLLD/TC37A/Tricore/Smu/Smu \
Libraries/infineon_libraries/iLLD/TC37A/Tricore/Smu/Std \
Libraries/infineon_libraries/iLLD/TC37A/Tricore/Src/Std \
Libraries/infineon_libraries/iLLD/TC37A/Tricore/Stm/Std \
Libraries/infineon_libraries/iLLD/TC37A/Tricore/Stm/Timer \
Libraries/infineon_libraries/iLLD/TC37A/Tricore/_Impl \
Libraries/infineon_libraries/iLLD/TC37A/Tricore/_Lib/DataHandling \
Libraries/infineon_libraries/iLLD/TC37A/Tricore/_Lib/InternalMux \
Libraries/infineon_libraries/iLLD/TC37A/Tricore/_PinMap \
Libraries/seekfree_libraries/common \
Libraries/seekfree_libraries \
Libraries/seekfree_peripheral \
USER \

